config/routes.rb
Rails.application.routes.draw do
 
  resources :submissions


  root :to => 'home#index'
  get '/admin', to: 'home#admin_index', as: :admin_index
  get '/ta', to: 'home#ta_index', as: :ta_index
  
  devise_for :users, :path=>"auth", :controllers=>{:registrations => :users}
  devise_scope :user do
    resources :users do
      collection do
        post 'bulk_add', as: :bulk_add
        post 'bulk_remove'
        get 'bulk'
      end
    end
  end
  resources :events do
    member do
      get 'signup'
      get 'submissions'
    end
    resources :slots do
      member do
        put 'signup'
        put 'remove_signup'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  #---Associations---
  has_many :slots
  has_many :submissions, dependent: :destroy
  
  #---Attributes---
  #attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username, :role
 
  
  #---Validations---
  before_validation :init_defaults

  validates :username, :uniqueness=>true
  validates :email, :uniqueness=>true
  validates :first_name, :last_name, :presence=>true
  validates :role, inclusion: {in: %w(ta student admin)}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  #################
  # Object methods
  #
  def init_defaults
    if self.email.blank?
      self.email = self.username+"@mit.edu"
    end
  end
  
  def admin?
    self.role=="admin"
  end
  
  def ta?
    self.role=="ta"
  end
  
  def student?
    self.role=="student"
  end
  
  def full_name
    self.first_name+" "+self.last_name
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    # GET /users
    def index
      unless current_user.admin?
        head :unauthorized
        return
      end
      @users = []
      if(params[:type]=="ta_or_admin")
        @users = User.where(:role=>["admin","ta"])
      elsif(params[:type]=="student")
        @users = User.where(:role=>["student"])      
      else
        @users = User.all
      end
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
    end
  
    # GET /users/1
    # GET /users/1.json
    def show
      unless current_user.admin?
        head :unauthorized
        return
      end
      
      @user = User.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  
    # GET /users/new
    # GET /users/new.json
    def new
      unless current_user.admin?
        head :unauthorized
        return
      end
      
      @user = User.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    end
  
    # GET /users/bulk
    def bulk
      unless current_user.admin?
        head :unauthorized
        return
      end
    end
    
    # POST /users/bulk_add.json
    def bulk_add
      #only admins can do this
      unless current_user.admin? 
        render nothing: true, status: :unauthorized and return
      end
      params[:students].each do |student_params|
        student = User.new(student_params.permit(:first_name, :last_name, :email, :username, :password))
        student.role = 'student'
        unless student.save
          puts "------------------"
          puts student.errors.full_messages
          render json: User.where(:role=>["student"]), status: :unprocessable_entity and return
        end
      end
      render json: User.where(:role=>["student"])
    end
  
    # POST /users/do_bulk_remove.json
    def bulk_remove
      #only admins can do this
      unless current_user.admin? 
        render nothing: true, status: :unauthorized and return
      end
      params[:students].each do |student_params|
        student = User.find_by_username(student_params[:username])
        unless student
          render json: User.where(:role=>["student"]), status: :unprocessable_entity and return
        end
        student.destroy
      end
      render json: User.where(:role=>["student"])
    end
    
    
    # GET /users/1/edit
    def edit
      unless ((current_user.admin?) or (current_user.id==params[:id].to_i))
        head :unauthorized
        return
      end
      @user = User.find(params[:id])
    end
  
    # POST /users
    # POST /users.json
    def create
      unless current_user.admin?
        head :unauthorized
        return
      end
      
      @user = User.new(user_params)
      @user.role = params[:user][:role]
      respond_to do |format|
        if @user.save
          format.html { redirect_to users_path, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /users/1
    # PUT /users/1.json
    def update
      unless current_user.admin? or current_user.id==params[:id].to_i
        head :unauthorized
        return
      end
      
      @user = User.find(params[:id])
      #don't change the password unless a new one is set
      new_params = user_params
      if new_params[:password].blank? && new_params[:password_confirmation].blank?
        new_params.delete(:password)
        new_params.delete(:password_confirmation)
      end
      #only admins can change user roles and no one can change their own role
      if current_user.admin? and current_user.id!=params[:id]
        @user.role = params[:user][:role]
      end
      respond_to do |format|
        if @user.valid? and @user.update(new_params)
          format.html { 
            if current_user.admin?
              redirect_to users_path, notice: 'User was successfully updated.'
            else
              redirect_to root_path, notice: "Account successfully updated"
             end
           }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      unless current_user.admin?
        head :unauthorized
        return
      end
      
      user = User.find(params[:id])
      user.destroy
      head :no_content
    end

    def user_params
        # :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username, :role
        params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
    end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
   <p class="alert-warning">Please fix the following errors</p>
  <% end %>
  <div class="form-group <% if @user.errors[:first_name].first %>has-error<%end%>">
    <%= f.label :first_name, :class=>"control-label"%>
    <%= f.text_field :first_name, :class=>"form-control"%>
    <span class="help-block"><%=@user.errors[:first_name].first%></span>
  </div>
  <div class="form-group <% if @user.errors[:last_name].first %>has-error<%end%>">
    <%= f.label :last_name, :class=>"control-label" %>
    <%= f.text_field :last_name, :class=>"form-control"%>
    <span class="help-block"><%=@user.errors[:last_name].first%></span>
  </div>
  <div class="form-group <% if @user.errors[:username].first %>has-error<%end%>">
    <%= f.label :username, :class=>"control-label" %>
    <%= f.text_field :username, :class=>"form-control"%>
    <span class="help-block"><%=@user.errors[:username].first%></span>
  </div>
  <div class="form-group <% if @user.errors[:password].first %>has-error<%end%>">
    <%= f.label :password, :class=>"control-label" %>
    <% unless @user.id.blank? %>
    <span class="text-muted" style="padding-left: 15px">if left blank, password is unchanged</span>
    <% end %>
    <%= f.password_field :password, :class=>"form-control"%>
    <span class="help-block"><%=@user.errors[:password].first%></span>
  </div>
  <div class="form-group <% if @user.errors[:password_confirmation].first %>has-error<%end%>">
    <%= f.label :password_confirmation, :class=>"control-label" %>
    <%= f.password_field :password_confirmation, :class=>"form-control"%>
    <span class="help-block"><%=@user.errors[:password_confirmation].first%></span>
  </div>
  <%if current_user.admin?%>
  <div class="form-group">
    <%= f.label :role %>
    <%= f.select(:role,['student','ta','admin'],{},{ :class=>"form-control"})%>
  </div>
  <%end%>
  <div class="actions">
    <%= f.submit "Update", :class=>"btn btn-primary"%>
    <a class="btn btn-default" href="<%=users_path%>">Cancel</a>
  </div>
<% end %>

app/views/users/bulk.html.erb
<div ng-controller="BulkUserCtrl" ng-init="init()">
  <h2>Add/Remove Students</h2>
  <div class="radio" ng-hide="true">
    <label>
      <input type="radio" ng_model="input_type"  value="csv" ng-change="validateInput()"></input>
      Last Name, First Name, Athena Username
    </label>
  </div>
  <div class=" radio">
    <label>
      <input type="radio" ng-model="input_type" value="list" ng-change="validateInput()"></input>
      MIT Class List
    </label>
  </div>
  <hr>
  <form class="clearfix">
    <div class="form-group">
    <textarea ui-codemirror="editorOptions" 
      placeholder="John, Doe, jdoe, 1234" class="form-control" rows=10
       ng-model="bulk_input" ng-change="validateInput()"></textarea>
    </div>
    <div class="form-group">
      <span ng-show="syntax_error" class="text-danger">Error parsing user, check your syntax</span>
      <p ng-show="errors['first_name']" class="text-danger">First name {{errors['first_name'][0]}}</p>
      <p ng-show="errors['last_name']" class="text-danger">Last name {{errors['last_name'][0]}}</p>
      <p ng-show="errors['username']" class="text-danger">Username {{errors['username'][0]}}</p>
      <p ng-show="errors['password']" class="text-danger">Password {{errors['password'][0]}}</p>
    </div>
  </form>
  <span class="lead" ng-show="input_type=='list' && error_msg==''">
    {{txt_added_students}} students + {{txt_removed_students}} dropped =  
    {{txt_added_students+txt_removed_students}} total</span>
  <span class="lead" ng-show="input_type=='csv' && error_msg==''">
    {{txt_added_students}} students total
  </span>
  <span class="lead text-danger" ng-show="error_msg!=''">
    {{error_msg}}
  </span>
  <div class="row">
    <!--Students to add-->
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Students to Add</div>
        <div class="panel-body">
          <table>
            <tbody>
              <tr ng-repeat="student in new_students">
                <td>{{student.first_name}} {{student.last_name}}</td>
              </tr>
            </tbody>
          </table>
          <hr/>
          <button type="button" class="btn btn-primary btn-block" ng-click="addStudents()"
            ng-disabled="busy || error_msg!='' || new_students.length==0">
            <i class="icon-spinner icon-spin" ng-show="busy"></i>Add Students
          </button>
        </div>
      </div>
    </div>
    <!--Students to remove-->
    <div class="col-md-6" ng-show="input_type=='list'">
      <div class="panel panel-default">
        <div class="panel-heading"> Students to Remove</div>
        <div class="panel-body">
          <table>
            <tbody>
              <tr ng-repeat="student in removed_students">
                <td>{{student.first_name}} {{student.last_name}}</td>
              </tr>
            </tbody>
          </table>
          <hr/>
          <button type="button" class="btn btn-danger btn-block" ng-click="removeStudents()"
            ng-disabled="busy || error_msg!='' || removed_students.length==0">
            <i class="icon-spinner icon-spin" ng-show="busy"></i>Remove Students
          </button>
        </div>
      </div>
    </div>
    <!--end-->
  </div>
  
  <a type="button" href="<%=users_path%>" class="btn btn-default" ng-disabled="busy">Done</a>
</div>

app/views/users/edit.html.erb
<%if current_user.id == @user.id%>
<h2>My Account</h2>
<% else %>
<h2>Editing user</h2>
<% end %>
<%= render 'form' %>

app/views/users/index.html.erb
<div ng-controller="UserCtrl" ng-init="refresh()">
  <h2>Users</h2>
  <table class="table">
    <thead>
        <th class="clickable" ng-click="sortBy('last_name')">Name</th>
        <th class="clickable" ng-click="sortBy('email')">Username</th>
        <th class="clickable" ng-click="sortBy('role')">Role</th>
        <th></th>
    </thead>
    <tbody>
      <tr ng-repeat="user in users | orderBy:predicate"  class="clickable">
        <td ng-click="editUser(user)">{{user.first_name}} {{user.last_name}}</td>
        <td ng-click="editUser(user)">{{user.email}}</td>
        <td ng-click="editUser(user)">{{user.role}}</td>
        <td><i class="icon-trash clickable" action="deleteUser(user)" confirmable></i></td>
      </tr>
    </tbody>
  </table>
  
  <a type="button" class="btn btn-primary" href="<%=new_user_path%>"><i class="icon-plus"></i> Add User</a>
  <a type="button" class="btn btn-default" href="<%=root_path%>">Home</a>
  <a type="button" class="btn btn-default pull-right" href="<%=bulk_users_path%>"><i class="icon-group"></i> Bulk Add</a>

</div>

app/views/users/new.html.erb
<h2>New user</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>