config/routes.rb
Rails.application.routes.draw do
 
  resources :submissions


  root :to => 'home#index'
  get '/admin', to: 'home#admin_index', as: :admin_index
  get '/ta', to: 'home#ta_index', as: :ta_index
  
  devise_for :users, :path=>"auth", :controllers=>{:registrations => :users}
  devise_scope :user do
    resources :users do
      collection do
        post 'bulk_add', as: :bulk_add
        post 'bulk_remove'
        get 'bulk'
      end
    end
  end
  resources :events do
    member do
      get 'signup'
      get 'submissions'
    end
    resources :slots do
      member do
        put 'signup'
        put 'remove_signup'
      end
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

    #---Associations---
    has_many :slots, dependent: :destroy
    has_many :submissions, dependent: :destroy
    
    #---Attributes---
    #attr_accessible :start_date, :end_date, :black_out_times, :name, :slot_length, :visible,
    #                :students_per_slot, :has_submissions, :submission_deadline
    
    #---Scopes---
    scope :active, -> {where(visible:true).where("end_date > ?",Time.now)}
    #---Validations---
    validates :name, :presence=>true, :uniqueness=>true
    validates :start_date, :end_date, :students_per_slot, :presence=>true
    validates :end_date, :presence=>true
    validates :slot_length, inclusion: {in: [5,10,15,20,30,40,45,60]}
    validates :students_per_slot, numericality: { only_integer: true, greater_than_or_equal_to: 1}
    validate :after_start_date
    
    
    def after_start_date
      if end_date and end_date <= start_date
        errors.add(:end_date, "must be later than start date");
      end
    end
    
    
    #################
    # Object Methods
    #
    
    def missing_students
      missing = []
      User.where(:role=>"student").each do |student|
        if slots.where(:student_id=>student.id).count == 0
          missing << student
        end
      end
      return missing
    end
    
    def missing_submissions
      if has_submissions==false
        return []
      end
      missing = []
      User.where(:role=>"student").each do |student|
        if submissions.where(:user_id=>student.id).count == 0
          missing << student
        end
      end
      return missing
    end
    
    def remove_bad_slots
      #remove any slots that aren't within the dates of the event
      early_slots = slots.where("start_time < ?", start_date)
      late_slots  = slots.where("start_time > ?", end_date)
      if(early_slots.length>0 or late_slots.length>0)
        Rails.logger.warn("### removing #{early_slots.length} early slots and #{late_slots.length} late slots from event #{self.id}")
      end
      early_slots.destroy_all
      late_slots.destroy_all
    end
    #--- custom overrides ----
    def as_json(options)
       event = super(options) 
       event[:slots] = self.slots.as_json(options)
       unless options[:limited]
        event[:missing_students] = missing_students.as_json
        event[:missing_submissions] = missing_submissions.as_json
       end
      
       return event
    end
    
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!
  
    # GET /events
    def index
      options = {}
      if not (current_user.ta? or current_user.admin?)
        options[:limited]=true
        options[:student]=current_user
        @events = Event.active.all
      else
        @events = Event.all
      end
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @events.as_json(options) }
      end
    end
  
    # GET /events/1
    def show
      options = {}
      if not (current_user.ta? or current_user.admin?)
        options[:limited]=true
        options[:student]=current_user
      end
      @event = Event.find(params[:id])
  
      respond_to do |format|
        format.html { 
          unless current_user.ta? or current_user.admin?
            head :unauthorized
            return
           end
           # show.html.erb
         }
        format.json { render json: @event.as_json(options) }
      end
    end
  
    # GET /events/1/signup
    def signup
      @event = Event.active.find(params[:id])
      if @event.has_submissions
        @submission = Submission.where(:user_id=>current_user.id, :event_id=>@event.id).first
        unless @submission
          @submission = Submission.new
        end
        @submission.event = @event
      end
    end
    
    # GET /events/new
    def new
      unless current_user.admin?
        head :unauthorized
        return
      end
      
      @event = Event.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @event }
      end
    end
  
    # GET /events/1/edit
    def edit
      unless current_user.admin?
        head :unauthorized
        return
      end
      @event = Event.find(params[:id])
    end
  
    # POST /events
    # POST /events.json
    def create
      unless current_user.admin?
        head :unauthorized
        return
      end
      @event = Event.new(event_params)
  
      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render json: @event, status: :created, location: @event }
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /events/1
    # PUT /events/1.json
    def update
      unless current_user.admin?
        head :unauthorized
        return
      end
      @event = Event.find(params[:id])
     
      respond_to do |format|
        if @event.update(event_params)
          #remove any slots that aren't within the bounds of the event dates
          @event.remove_bad_slots
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { head :no_content,  notice: 'Event was successfully updated.' }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      unless current_user.admin?
        head :unauthorized
        return
      end
      event = Event.find(params[:id])
      event.destroy
      head :no_content
    end
    
    # GET /events/1/submissions
    def submissions
      unless current_user.admin? or current_user.ta?
        head :unauthorized
        return
      end
      @event = Event.find(params[:id])
      unless @event.has_submissions
        head :unprocessable_entity
        return
      end
    end


    def event_params
        # :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username, :role
        params.require(:event).permit(:start_date, :end_date, :black_out_times, :name, :slot_length, :visible,
                       :students_per_slot, :has_submissions, :submission_deadline)
    end
  end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<form>
  <!--Event Name -->
  <div class="form-group" ng-class="errors.name | errorClass">
    <label class="control-label"> Name </label>
    <input type="text" class="form-control" placeholder="Event name" ng-model="event.name">
    <span class="help-block">{{errors.name[0]}}</span>
  </div>
  
  <!-- Event Start Date-->
  <div class="form-group" ng-class="errors.start_date | errorClass">
    <label class="control-label"> Start Date </label>
    <div class="input-group">
      <input type="text" datepicker-popup="dd-MMMM" ng-model="event.start_date" placeholder="Start date"
        class="form-control" show-weeks="false"/>
      <span class="input-group-addon"><i class="icon-calendar"></i></span>
    </div>
    <span class="help-block">{{errors.start_date[0]}}</span>
  </div>
  <!--Event End Date -->
  <div class="form-group" ng-class="errors.end_date | errorClass">
    <label class="control-label"> End Date </label>
    <div class="input-group">
      <input type="text" datepicker-popup="dd-MMMM" ng-model="event.end_date" placeholder="End date"
        class="form-control" show-weeks="false"/>
      <span class="input-group-addon"><i class="icon-calendar"></i></span>
    </div>
    <span class="help-block">{{errors.end_date[0]}}</span>
  </div>
  <!-- Slot Length-->
  <div class="form-group" ng-class="errors.slot_length | errorClass">
    <label class="control-label"> Slot Length (minutes) </label>
    <%=select_tag 'slot_length', options_for_select([5,10,15,20,30,40,45,60]), {:class=>"form-control", 'ng-model'=>"event.slot_length"}%>
    <span class="help-block">{{errors.slot_length[0]}}</span>
  </div>
  <!--Students Per Slot -->
   <div class="form-group" ng-class="errors.students_per_slot | errorClass">
    <label class="control-label"> Students Per Slot </label>
      <input type="text" ng-model="event.students_per_slot" placeholder="students per slot" 
        class="form-control"/>
      <span class="help-block">{{errors.students_per_slot[0]}}</span>
  </div>
  <!--Require submission -->
  <div class="form-group">
    <label class="control-label">Require Submission</label>
    <input type="checkbox" ng-model="event.has_submissions"></input>
  </div>
  <div class="form-group" ng-show="event.has_submissions">
    <label class="control-label">Submission Deadline</label>
    <div class="row">
      <div class="input-group col-md-6">
        <input type="text" datepicker-popup="dd-MMMM-yyyy" ng-model="event.submission_deadline" placeholder="Deadline"
          class="form-control" show-weeks="false"/>
        <span class="input-group-addon"><i class="icon-calendar"></i></span>
      </div>
      <div class="col-md-4" style="margin-top: -37px">
      <timepicker ng-model="event.submission_deadline" hour-step="1"
          show-meridian="true"></timepicker>
      </div>
    </div>
  </div>
</form>

app/views/events/edit.html.erb
<div ng-controller="EventCtrl" ng-init="init(<%=@event.id%>)">

<h2>Editing Event</h2>
<p class="lead text-warning">Any slots that are not in the new date range will be removed</p>
<%= render 'form' %>
<div class="actions">
    <button type="button" class="btn btn-primary" ng-click="updateEvent()">Update event</button>
    <a class="btn btn-default" href="<%=event_path%>">Cancel</a>
  </div>
  
</div>

app/views/events/index.html.erb
<div ng-controller="EventsCtrl" ng-init="refresh()">
  <h2>Events</h2>
  <table class="table">
    <thead>
        <th>Name</th>
        <th>Dates</th>
        <th>Slots</th>
        <th ng-show="admin"></th>
    </thead>
    <tbody>
      <tr ng-repeat="event in events"  class="clickable">
        <td ng-click="showEvent(event)">{{event.name}}</td>
        <td ng-click="showEvent(event)">{{event.dateRange() | dateRange}}</td>
        <td ng-click="showEvent(event)">{{event.slot_length}} min</td>
        <td ng-show="admin">
          <i class="icon-trash clickable" action="deleteEvent(event)" confirmable></i>
        </td>
      </tr>
    </tbody>
  </table>
  
  <a type="button" class="btn btn-primary" ng-show="admin"
    href="<%=new_event_path%>"><i class="icon-plus"></i> Add Event</a>
  <a type="button" class="btn btn-default" href="<%=root_path%>" ng-show="admin">Home</a>
</div>

app/views/events/new.html.erb
<div ng-controller="EventCtrl" ng-init="init()">
<h2>New event</h2>

<%= render 'form' %>
<div class="actions">
    <button type="button" class="btn btn-primary" ng-click="createEvent()">Create event</button>
    <a class="btn btn-default" href="<%=events_path%>">Cancel</a>
</div>
</div>

app/views/events/show.html.erb
<div ng-controller="EventCtrl" ng-init="init('<%=@event.id%>')">
  <div style="position:relative">
    <!--Event Name-->
    <h2>{{event.name}}</h2>
    <!--Hide or Show Event (admin only)-->
    <button type="button" class="btn btn-success btn-lg event-action"
      ng-show="event.visible==false && admin" ng-click="showEvent()">
      <i class="icon-eye-open"></i>   Make Visible</button>
    <button type="button" class="btn btn-danger btn-lg event-action"
      ng-show="event.visible && admin" ng-click="hideEvent()">
      <i class="icon-eye-close"></i>   Hide</button>
  </div>
  <!--status of # slots filled, and students missing-->
  <p class="lead">{{event.slots_filled}} of {{event.slots.length}} slots filled. 
  <span ng-pluralize count=event.missing_students.length ng-class="event.missing_students.length>0 | warningClass"
                     when="{'0': 'No students missing.',
                            '1': '1 student missing.',
                            'other': '{{event.missing_students.length}} students missing'}"
  </span></p>
  <!--add slot form-->
   <form class="form-inline clearfix" role="form">
    <!--date select-->
    <div class="form-group">
      <label class="sr-only">Date</label>
      <select ng-model="slot.start_date"  class="form-control" 
       ng-options="date  | abbrevDate for date in event.dates"></select>
    </div>
    <!-- time select -->
    <div class="form-group" style="max-width:50%">
      <label class="sr-only">Time</label>
      <timepicker ng-model="slot.start_time" hour-step="1"
        minute-step="event.slot_length" show-meridian="true" read-only="true"></timepicker>
    </div>
    <!--location select-->
    <div class="form-group" ng-class="errors.location | errorClass">
      <label class="sr-only">Location</label>
      <input type="text" ng-model="slot.location" class="form-control" placeholder="Location">
    </div>
    <!--standard slot creation button (TA only)-->
    <button type="button" class="btn btn-success " ng-click="createSlot()" ng-show="ta">
      <i class="icon-plus"></i>  Add slot</button>
    <!--universal slot creation button (admin only)-->
    <div ng-show="admin">
      <button type="button" class="btn btn-success" ng-click="createSlot()">
        <i class="icon-plus"></i>   Add slot for 
      </button>
      <select  ng-model="taForSlot" class="form-control" ng-change = "errors = []" style="max-width:25%"
        ng-options="ta | name for ta in availableTAs"></select>
    </div>
    <!--validation errors-->
    <div ng-show="errors['ta'] && admin" class="form-group text-danger">{{taForSlot | name}} is {{errors['ta'][0] }}</div>
    <div ng-show="errors['ta'] && ta" class="form-group text-danger">you are {{errors['ta'][0] }}</div>
    <span ng-show="errors['ta'] && errors['location']" class="form-group text-danger" > and </span>
    <div ng-show="errors['location']" class="form-group text-danger">the location {{errors['location'][0]}}</div>
  </form>
  
  <hr/>
  <!--existing slots table-->
   <table class="table">
    <thead>
        <th>Time</th>
        <th>TA</th>
        <th>Student</th>
        <th>Location</th>
        <th></th>
    </thead>
    <tbody>
      <tr ng-repeat="slot in event.slots | orderBy:'start_time'" >
        <!--slot time-->
        <td>{{slot.start_time | time}}</td>
        <!--slot ta-->
        <td><a href="mailto:{{slot.ta.email}}">{{slot.ta | name}}</a></td>
        <!--slot student-->
        <td><a href="mailto:{{slot.student.email}}" ng-show="slot.student">{{slot.student | name}} </a>
          <span ng-show="admin && slot.student!=null">
            <i class="icon-remove remove clickable"
            action="removeSignup(slot)" confirmable></i>
          </span>
          <!--add missing student to a slot (admin only)-->
           <select ng-model="slot.student"  class="form-control" 
              ng-show="slot.student ==null && admin" ng-change="assignSlot(slot)"
              ng-options="student  | name for student in event.missing_students"></select>
        </td>
        <!--slot location-->
        <td>{{slot.location}}</td>
        <td  ng-show="removableSlot(slot)">
          <i class="icon-trash clickable" action="deleteSlot(slot)" confirmable></i></td>
      </tr>
    </tbody>
  </table>
  <hr/>
  <div class="row">
    <div class="col-md-6">
      <!-- list of missing students -->
      <span class="lead" ng-show="event.missing_students.length>0">Missing Signups:
          <a href="mailto:{{event.missing_students | emails}}"><i class="icon-envelope clickable" ></i></a>
      </span>
      <ul style="font-size: 1.3em" ng-show="event.missing_students.length>0">
        <li class="list-unstyled"
        ng-repeat="student in event.missing_students | orderBy:'last_name'">
          <a href="mailto:{{student.email}}">{{student | name}}</a></li>
      </ul> 
    </div>
    <div class="col-md-6" ng-show="event.has_submissions">
      <!-- list of missing submissions -->
      <span class="lead" ng-show="event.missing_submissions.length>0">Missing Submissions:
          <a href="mailto:{{event.missing_submissions | emails}}"><i class="icon-envelope clickable" ></i></a>
      </span>
      <ul style="font-size: 1.3em" ng-show="event.missing_submissions.length>0">
        <li class="list-unstyled"
        ng-repeat="student in event.missing_submissions | orderBy:'last_name'">
          <a href="mailto:{{student.email}}">{{student | name}}</a></li>
      </ul> 
    </div>
  </div>
 
  <a type="button" class="btn btn-primary" href = "<%=edit_event_path%>" ng-show="admin">Edit Event</a>
  <a  class="btn btn-default" href="<%=events_path%>">Back</a>
  <a class="btn btn-default pull-right" href="<%=submissions_event_path%>">
    <i class="icon-file-text"></i>  Submissions</a>
</div>

app/views/events/signup.html.erb
<div ng-controller="SignupCtrl" ng-init="init('<%=@event.id%>')">
  <div style="position:relative">
  <h2>{{event.name}}</h2>
  
   <div ng-show="!signup_enabled" class="clearfix">
     <span class="lead">Your signup is on {{slot.start_time.format("mmm dd")}} at
        {{slot.start_time.format("h:MM TT")}} <br> with {{slot.ta | name}} in {{slot.location}}
     </span>
     <button type="button" class="btn btn-danger pull-right" ng-show="changeable(slot)" 
      ng-click="removeSignup()">
       <i class="icon-remove"></i>  Cancel Signup
     </button>
   </div>
   <!--file submission -->
   <div class="row" style="margin-top: 10px" ng-show="event.has_submissions">
     <!-- live submissions (can still submit)-->
     <div class="col-md-offset-1 col-md-8 well" ng-show="acceptingSubmissions()" >
       <div ng-show="!submission">
         <% if @event.has_submissions%>
         <%=form_for @submission, :html => {:multipart => true, :class=>"form-inline"} do |f| %>
          <h5>Submit your code by <strong>{{event.submission_deadline.format("mmm dd, h:MM TT")}}</strong>:</h5>
          <%=f.hidden_field :event_id%>
          <form-group>
            <%=f.file_field :file%>
          </form-group>
          <form-group >
            <%=f.submit "Upload submission", :class=>"btn btn-primary", :style=>"margin-top: 10px"%>
          </form-group>
         <%end%>
         <%end%>
       </div>
       <div ng-show="submission">
         <h5>Submit your code by <strong>{{event.submission_deadline.format("mmm dd, h:MM TT")}}</strong>:</h5>
         <span class="lead text-success">Code Received</span>
         <a class="btn btn-default" href="{{submission.file.url}}"
          popover="download" popover-trigger="mouseenter" 
          popover-popup-delay="1000" popover-placement="bottom"><i class="icon-download-alt"></i></a>
         <button class="btn btn-default" ng-click="removeSubmission()"
          popover="remove submission" popover-trigger="mouseenter" 
          popover-popup-delay="1000" popover-placement="bottom">
           <i class="icon-remove"></i></button>
       </div>
     </div>
     <!--submission period over-->
     <div class="col-md-offset-1 col-md-8 well" ng-show="!acceptingSubmissions()" >
       <!-- successful submission-->
       <div ng-show="submission">
         <span class="lead text-success">Submission Received</span>
         <a class="btn btn-default pull-right"
           href="{{submission.file.url}}">
           <i class="icon-download-alt"></i>  Download</a>
       </div>
       <!--missing submission-->
       <div ng-show="!submission">
         <p class="lead text-danger">Missed deadline for submission</p>
       </div>
    </div>
   </div>
   <table class="table">
    <thead>
        <th>Time</th>
        <th>Student</th>
    </thead>
    <tbody>
      <tr ng-repeat="slot in event.slots | orderBy:'start_time'" >
        <td>{{slot.start_time | time}}</td>
        <td> 
          <button type="button" class="btn btn-default" 
            ng-show="slot.student==null && signup_enabled && changeable(slot)" ng-click="signup(slot)">Sign Up</button>
          <span ng-show="slot.student!=null">{{slot.student | name}}</span>
        </td>
      
      </tr>
    </tbody>
  </table>
  
 
</div>

app/views/events/submissions.html.erb
<div>
  <h2>Submissions for <span class="text-muted"><%=@event.name%></span></h2>
  <table class="table">
    <thead>
        <th>Name</th>
        <th>Submitted</th>
        <th></th>
    </thead>
    <tbody>
      <% @event.submissions.each do |submission| %>
        <tr>
          <td><%=submission.user.full_name%></td>
          <td><%=submission.created_at.strftime("%b %d %H:%M")%></td>
          <td><a href="<%=url_for(submission.file)%>",  class="btn btn-default">
              <i class="icon-download-alt"></i> Download</a>
          </td>
      </tr>
      <%end%>
    </tbody>
  </table>
  
 
</div>